#Whether to log the dirt block on common setup
logDirtBlock = true
#A magic number
#Range: > 0
magicNumber = 42
#What you want the introduction message to be for the magic number
magicNumberIntroduction = "The magic number is... "
# 
#A list of items that can use on side of terracotta golem.
#You can add other item to this list, it's texture must named be the same as item id.
items = ["minecraft:iron_ingot"]
#Whether to enable the health value display override for the weak potion effect
useWeakPoisonOverLay = true
#The number of #ancient_boat_need_1 that need to be held in hand to repair the ancient boat.
#Range: 0 ~ 32767
"count of [ancient_boat_need_1]" = 5
#The number of #ancient_boat_need_2 that need to be held in hand to repair the ancient boat.
#Range: 0 ~ 32767
"count of [ancient_boat_need_2]" = 2
#The number of #ancient_chest_boat_need_1 that need to be held in hand to repair the ancient chest boat.
#Range: 0 ~ 32767
"count of [ancient_chest_boat_need_1]" = 5
#The number of #ancient_chest_boat_need_2 that need to be held in hand to repair the ancient chest boat.
#Range: 0 ~ 32767
"count of [ancient_chest_boat_need_2]" = 1
# 
#Greatly enhance effects and monsters. Use for that games using mods with additional cultivation content- such as Curios, any Skill mods or Guns mods.
#true: Always enabled this mode.
#default: Automatically determine whether to enable it based on the player's combat performance.
#false: Never enabled this mode.
powerBattleMode = "default"
#After opening, you can right-click to harvest the crops of the module
rightClickHarvest = true
#After being turned off, when the Power Battle Mode is enabled, the prompt field will no longer be displayed in the game
powerBattleModeHint = true
# 
#We apologize for making players excessively capable. 
#For the sake of balance, you can use this option to synchronously strengthen some of the original enemies.
#Configure which enemies can be strengthened in the entity tags file, to all the functions.
needStrengthenTheEnemies = false
# 
#Configure the attack damage multiplier of powered mobs be increased based on the target's health value
useDynamicDamage = false
# 
#Set the maximum attack damage multiplier of powered mobs
#Example: [0.5, 2.0, 5.0],it must have 3 number,to normal mobs,elite mobs,mod bosses.
maximumDamageMultiplier = [0.5, 2.0, 5.0]
# 
#Set the attack damage multiplier per target's health
#Example: [0.002, 0.006, 0.02],it must have 3 number,to normal mobs,elite mobs,mod bosses.
#Use gradient calculation. For example, for elite mobs, follow the default value:
# the damage multiplier increases by 0.002 per health point until it reaches 1.5x (1+0.5), 
#then the damage multiplier increases by 0.006 per health point until it reaches 3.0x (1+2.0). 
damageMultiplierPerHealth = [0.002, 0.006, 0.02]
# 
#Configure the min value when powered mobs attack
useMinDamage = false
# 
#Set the min value when powered mobs attack
#Example: [1.0, 2.0, 2.5],it must have 3 number,to normal mobs,elite mobs,mod bosses.
minDamageValue = [1.0, 2.0, 2.5]
# 
#Configure the damage multiplier taken by mobs will decrease as the base damage value increases.
useHigh-DamageCounteraction = true
# 
#Set the maximum damage divisor taken by mobs
#For example,if set 9.0 to a mob, damage taken by mobs will min become 0.1x.
#Example: [7.0, 11.0, 15.0],it must have 3 number,to normal mobs,elite mobs,mod bosses.
maximumDamageDivisor = [7.0, 11.0, 15.0]
# 
#Set the attack damage divisor per damage taken by mobs
#Example: [0.04, 0.05, 0.08],it must have 3 number,to normal mobs,elite mobs,mod bosses.
damageDivisorPerDamage = [0.04, 0.05, 0.08]
#Set the probability of the sniffer beast mining Mod items
#Range: 0.0 ~ 1.0
mininProbability = 0.5

[ReverseNormalEffect]
	#Potion effects that can be reversed. Effect in this Map will be remove every tick. 
	#It does not prevent the application of effects, so it may not completely block the activation of harmful potion effects sometimes if only use this.
	#"input-effect-n" means ID of the effect to be converted,"output-effect-n" means ID of the effect that conversion result.
	#Format: [["input-effect-1", "output-effect-1"], ["input-effect-2", "output-effect-2"], ...etc]
	reverseNormalEffect = [["minecraft:bad_omen", "minecraft:hero_of_the_village"], ["minecraft:unluck", "minecraft:luck"], ["minecraft:glowing", "minecraft:invisibility"], ["minecraft:slowness", "minecraft:speed"], ["minecraft:levitation", "minecraft:slow_falling"], ["minecraft:darkness", "minecraft:conduit_power"], ["minecraft:mining_fatigue", "minecraft:haste"], ["minecraft:weakness", "minecraft:strength"], ["minecraft:poison", "immortalers_delight:lingering_infusion"], ["minecraft:hunger", "immortalers_delight:satiated"], ["minecraft:wither", "immortalers_delight:vitality"], ["minecraft:nausea", "farmersdelight:nourishment"], ["minecraft:blindness", "minecraft:night_vision"], ["immortalers_delight:weak_poison", "farmersdelight:comfort"], ["immortalers_delight:weak_wither", "minecraft:regeneration"], ["twilightforest:frosty", "immortalers_delight:cool"], ["aether:inebriation", "aether:remedy"]]

[ReverseInstantEffect]
	#It takes effect when the effect in this Map is being applied, blocking its application and reversing it.
	#It only takes effect when the effect is being added, so it alone cannot convert existing effects.
	#"input-effect-n" means ID of the effect to be converted,"output-effect-n" means ID of the effect that conversion result.
	#Format: [["input-effect-1", "output-effect-1"], ["input-effect-2", "output-effect-2"], ...etc]
	reverseInstantEffect = [["minecraft:instant_damage", "minecraft:instant_health"], ["minecraft:blindness", "minecraft:night_vision"]]

